name: tfsec

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      TIER_PATH:
        required: true
        type: string

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ${{ inputs.TIER_PATH }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
