name: deploy

on:
  push:
    branches:
      - main

jobs:

  test:
    name: test
    uses: ./.github/workflows/tier.yml
    with:
      ENVIRONMENT: test
      TIER_PATH: tiers/test
      TERRAFORM_PATH: terraform
  terraform-test:
    name: terraform-test
    needs: test
    uses: ./.github/workflows/terraform_deploy.yml
    with:
      ENVIRONMENT: test
      TERRAFORM_VERSION: '1.4.6'
      TIER_PATH: tiers/test
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  terratest-test:
    name: terratest-test
    needs: terraform-test
    uses: ./.github/workflows/terratest.yml
    with:
      ENVIRONMENT: test
      TERRAFORM_VERSION: '1.4.6'
      TIMEOUT: 10s
      FUNCTION: TestAwsS3Test
      AWS_DEFAULT_REGION: ap-southeast-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  
  # prod-approval:
  #   name: prod-approval
  #   needs: terratest-test
  #   steps:
  #     - uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: user1,user2,org-team1
  #         minimum-approvals: 1
  #         issue-title: "Deploying v1.3.5 to prod from staging"
  #         issue-body: "Please approve or deny the deployment of version v1.3.5."
  #         exclude-workflow-initiator-as-approver: false
  #         additional-approved-words: ''
  #         additional-denied-words: ''

  prod:
    name: prod
    needs: terratest-test
    uses: ./.github/workflows/tier.yml
    with:
      ENVIRONMENT: prod
      TIER_PATH: tiers/prod
      TERRAFORM_PATH: terraform
  terraform-prod:
    name: terraform-prod
    needs: prod
    uses: ./.github/workflows/terraform_deploy.yml
    with:
      ENVIRONMENT: prod
      TERRAFORM_VERSION: '1.4.6'
      TIER_PATH: tiers/prod
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  terratest-prod:
    name: terratest-prod
    needs: terraform-prod
    uses: ./.github/workflows/terratest.yml
    with:
      ENVIRONMENT: prod
      TERRAFORM_VERSION: '1.4.6'
      TIMEOUT: 10s
      FUNCTION: TestAwsS3Prod
      AWS_DEFAULT_REGION: ap-southeast-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
