name: deploy

on:
  push:
    branches:
      - main

env:
  TEST_ENVIRONMENT: test
  PROD_ENVIRONMENT: prod
  TERRAFORM_VERSION: '1.4.6'
  TEST_PATH: tiers/test
  PROD_PATH: tiers/prod
  TERRAFORM_PATH: terraform
  TIMEOUT: 10S
  AWS_DEFAULT_REGION: ap-southeast-1
  TEST_FUNCTION: TestAwsS3Test
  PROD_FUNCTION: TestAwsS3Prod

jobs:

  test:
    name: test
    uses: ./.github/workflows/tier.yml
    with:
      ENVIRONMENT: $TEST_ENVIRONMENT
      TIER_PATH: $TEST_PATH
      TERRAFORM_PATH: $TERRAFORM_PATH
  terraform-test:
    name: terraform-test
    needs: test
    uses: ./.github/workflows/terraform_deploy.yml
    with:
      ENVIRONMENT: $TEST_ENVIRONMENT
      TERRAFORM_VERSION: $TERRAFORM_VERSION
      TIER_PATH: $TEST_PATH
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  terratest-test:
    name: terratest-test
    needs: terraform-test
    uses: ./.github/workflows/terratest.yml
    with:
      ENVIRONMENT: $TEST_ENVIRONMENT
      TERRAFORM_VERSION: $TERRAFORM_VERSION
      TIMEOUT: $TIMEOUT
      FUNCTION: $TEST_FUNCTION
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  
  # prod-approval:
  #   name: prod-approval
  #   needs: terratest-test
  #   steps:
  #     - uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: user1,user2,org-team1
  #         minimum-approvals: 1
  #         issue-title: "Deploying v1.3.5 to prod from staging"
  #         issue-body: "Please approve or deny the deployment of version v1.3.5."
  #         exclude-workflow-initiator-as-approver: false
  #         additional-approved-words: ''
  #         additional-denied-words: ''

  prod:
    name: prod
    needs: terratest-test
    uses: ./.github/workflows/tier.yml
    with:
      ENVIRONMENT: $PROD_ENVIRONMENT
      TIER_PATH: $PROD_PATH
      TERRAFORM_PATH: $TERRAFORM_PATH
  terraform-prod:
    name: terraform-prod
    needs: prod
    uses: ./.github/workflows/terraform_deploy.yml
    with:
      ENVIRONMENT: $PROD_ENVIRONMENT
      TERRAFORM_VERSION: $TERRAFORM_VERSION
      TIER_PATH: $PROD_PATH
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  terratest-prod:
    name: terratest-prod
    needs: terraform-prod
    uses: ./.github/workflows/terratest.yml
    with:
      ENVIRONMENT: $PROD_ENVIRONMENT
      TERRAFORM_VERSION: $TERRAFORM_VERSION
      TIMEOUT: $TIMEOUT
      FUNCTION: $PROD_FUNCTION
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
