name: testing

on:
  push:
    branches:
      - feature/*

env:
  ENVIRONMENT: testing
  TERRAFORM_VERSION: '1.4.6'
  TIMEOUT: 10m
  FUNCTION: TestAwsS3Dev
  AWS_DEFAULT_REGION: ap-southeast-1
  DEV_PATH: ./tiers/dev
  TERRAFORM_PATH: ./terraform

jobs:

  tier:
    name: tier
    uses: ./.github/workflows/templates/tier.yml
    with:
      TIERPATH: $DEV_PATH
      TERRAFORM_PATH: $TERRAFORM_PATH
  
  terratest:
    name: terratest
    uses: ./.github/workflows/templates/terratest.yml
    with:
      ENVIRONMENT: $ENVIRONMENT
      TERRAFORM_VERSION: $TERRAFORM_VERSION
      TIMEOUT: $TIMEOUT
      FUNCTION: $FUNCTION
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
